# Generated by Django 4.1.3 on 2022-12-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reciever_name',
            new_name='userA',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sender_name',
            new_name='userB',
        ),
    ]
